# Generated by Django 4.2.2 on 2023-09-18 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ('account_type',),
            },
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ('district',),
            },
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=250, unique=True)),
                ('district_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('pnumber', models.CharField(max_length=13)),
                ('mailid', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=250)),
                ('debit_card', models.BooleanField(default=False)),
                ('credits_card', models.BooleanField(default=False)),
                ('online_banking', models.BooleanField(default=False)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.account')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankapp.banks')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankapp.district')),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='banks',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.district'),
        ),
    ]
