# Generated by Django 4.2.2 on 2023-09-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banks',
            old_name='branch',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='district_name',
            new_name='name',
        ),
    ]
